apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-notes-app
  labels:
    app: react-notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-notes-app
  template:
    metadata:
      labels:
        app: react-notes-app
    spec:
      containers:
      - name: react-notes-app
        image: tushardubey/notes_app:latest
        ports:
        - containerPort: 3000
