apiVersion: v1
kind: Service
metadata:
  name: my-react-app
spec:
  type: NodePort
  selector:
    app: react-notes-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 32000
